import type { Lang } from "./text";

// Every new desk control has all six translations. Order: en, zh, es, ko, vi, ja.
const copy = {
  workspace: [
    "Your student workspace",
    "学习与生活，一桌安排",
    "Tu espacio de estudiante",
    "나의 학생 공간",
    "Góc học tập của bạn",
    "学生生活のワークスペース",
  ],
  today: ["Today", "今日", "Hoy", "오늘", "Hôm nay", "今日"],
  campus: ["Campus", "校园", "Campus", "캠퍼스", "Trường học", "キャンパス"],
  schools: ["Schools", "学校", "Escuelas", "학교", "Trường học", "学校"],
  town: [
    "Explore Eugene",
    "探索尤金",
    "Explorar Eugene",
    "유진 둘러보기",
    "Khám phá Eugene",
    "ユージンを探す",
  ],
  guide: [
    "Student guide",
    "学生指南",
    "Guía estudiantil",
    "학생 안내",
    "Cẩm nang sinh viên",
    "学生ガイド",
  ],
  gpa: ["GPA calculator", "绩点计算", "Calculadora de GPA", "학점 계산기", "Tính GPA", "GPA計算"],
  townShort: ["Explore", "周边", "Explorar", "둘러보기", "Khám phá", "周辺"],
  guideShort: ["Guide", "指南", "Guía", "안내", "Cẩm nang", "ガイド"],
  gpaShort: ["GPA", "绩点", "GPA", "학점", "GPA", "GPA"],
  level: ["School level", "学段", "Nivel educativo", "학교 단계", "Bậc học", "学校区分"],
  language: ["Language", "语言", "Idioma", "언어", "Ngôn ngữ", "言語"],
  local: [
    "Stored in this browser",
    "保存在当前浏览器",
    "Guardado en este navegador",
    "이 브라우저에 저장",
    "Lưu trong trình duyệt này",
    "このブラウザに保存",
  ],
  privacy: [
    "No account. Your plans stay here, not in the cloud.",
    "无需登录。课表和待办只存在这里，不会同步到云端。",
    "Sin cuenta. Tus planes se guardan aquí, no en la nube.",
    "계정 없이 사용해요. 일정은 클라우드가 아닌 이곳에만 저장돼요.",
    "Không cần tài khoản. Kế hoạch chỉ lưu tại đây, không đồng bộ lên đám mây.",
    "アカウント不要。予定はクラウドではなく、ここにだけ保存されます。",
  ],
  storageError: [
    "Could not save. Keep this tab open and check your browser storage settings.",
    "暂时无法保存。请先保留此页面，并检查浏览器的存储设置。",
    "No se pudo guardar. Mantén esta pestaña abierta y revisa el almacenamiento del navegador.",
    "저장하지 못했어요. 이 탭을 열어 두고 브라우저 저장 설정을 확인하세요.",
    "Không lưu được. Giữ tab này mở và kiểm tra cài đặt lưu trữ.",
    "保存できません。タブを開いたまま、ブラウザの保存設定を確認してください。",
  ],
  welcome: [
    "Make room for your day.",
    "今天，从这里开始。",
    "Organiza tu día.",
    "오늘을 차근차근.",
    "Bắt đầu ngày mới tại đây.",
    "今日を、ここから。",
  ],
  intro: [
    "Classes, little to-dos, and life around Eugene. All in one place.",
    "上课、待办、校园生活，放在一起，安排更轻松。",
    "Clases, tareas y vida en Eugene. Todo en un solo lugar.",
    "수업, 할 일, 유진에서의 생활을 한곳에서 정리하세요.",
    "Lịch học, việc cần làm và cuộc sống tại Eugene, tất cả ở một nơi.",
    "授業も、やることも、ユージンでの暮らしも。ひとつの場所に。",
  ],
  setup: [
    "Make this desk yours",
    "先选好你的学段",
    "Personaliza tu espacio",
    "나에게 맞는 공간",
    "Tùy chỉnh góc học tập",
    "自分に合ったデスクに",
  ],
  setupHint: [
    "Use the school-level and language menus to choose what you see. Each level keeps its own plans.",
    "通过学段和语言菜单切换内容；每个学段的课表、待办和成绩独立保存。",
    "Elige nivel e idioma en los menús. Cada nivel guarda sus propios planes.",
    "학교 단계와 언어를 선택하세요. 단계별 일정은 따로 저장돼요.",
    "Chọn bậc học và ngôn ngữ trong menu. Mỗi bậc có kế hoạch riêng.",
    "メニューで学校区分と言語を選べます。予定は学校区分ごとに保存されます。",
  ],
  gotIt: ["Got it", "知道了", "Entendido", "확인", "Đã hiểu", "了解"],
  pending: ["To do", "待完成", "Pendientes", "할 일", "Cần làm", "未完了"],
  done: ["Completed", "已完成", "Completadas", "완료", "Hoàn thành", "完了"],
  classes: ["Classes today", "今日课程", "Clases de hoy", "오늘 수업", "Lớp hôm nay", "今日の授業"],
  saved: [
    "Saved places",
    "收藏地点",
    "Lugares guardados",
    "저장한 장소",
    "Địa điểm đã lưu",
    "保存した場所",
  ],
  tasks: [
    "Your to-do list",
    "我的待办",
    "Tus tareas",
    "나의 할 일",
    "Việc cần làm",
    "やることリスト",
  ],
  taskHint: [
    "Start small. Write down the next thing you need to do.",
    "把下一件要做的事记下来，不用一次安排好所有事。",
    "Empieza con algo pequeño. Anota lo siguiente que necesitas hacer.",
    "작은 일부터 시작해요. 다음에 할 일을 적어 보세요.",
    "Bắt đầu từ việc nhỏ. Ghi lại việc tiếp theo cần làm.",
    "小さなことから。次にやることをひとつ書いてみましょう。",
  ],
  taskPlaceholder: [
    "e.g. Review biology notes",
    "例如：整理生物课笔记",
    "Ej.: repasar los apuntes de biología",
    "예: 생물학 필기 복습",
    "Ví dụ: ôn ghi chép môn Sinh",
    "例：生物のノートを見直す",
  ],
  add: ["Add", "添加", "Añadir", "추가", "Thêm", "追加"],
  all: ["All", "全部", "Todas", "전체", "Tất cả", "すべて"],
  noTasks: [
    "A little room to breathe.",
    "暂时没有待办。",
    "Un momento para respirar.",
    "잠시 여유를 가져요.",
    "Tạm thời chưa có việc cần làm.",
    "今は、ひと息。",
  ],
  noFiltered: [
    "Nothing in this view yet.",
    "这里还没有条目。",
    "Todavía no hay tareas aquí.",
    "아직 항목이 없어요.",
    "Chưa có mục nào ở đây.",
    "ここにはまだ項目がありません。",
  ],
  taskLimit: [
    "You can keep 20 tasks. Remove an old one to add another.",
    "最多保留 20 条待办，删除不需要的条目后可以继续添加。",
    "Puedes guardar 20 tareas. Elimina una para añadir otra.",
    "최대 20개까지 저장할 수 있어요. 기존 항목을 삭제한 뒤 추가하세요.",
    "Lưu tối đa 20 việc. Xóa một việc cũ để thêm việc mới.",
    "20件まで保存できます。不要な項目を削除して追加してください。",
  ],
  added: [
    "Added to your list.",
    "已添加到待办。",
    "Añadida a tu lista.",
    "목록에 추가했어요.",
    "Đã thêm vào danh sách.",
    "リストに追加しました。",
  ],
  deleted: [
    "Item deleted.",
    "已删除。",
    "Elemento eliminado.",
    "삭제했어요.",
    "Đã xóa.",
    "削除しました。",
  ],
  undo: ["Undo", "撤销", "Deshacer", "실행 취소", "Hoàn tác", "元に戻す"],
  restored: [
    "Restored.",
    "已恢复。",
    "Restaurado.",
    "복원했어요.",
    "Đã khôi phục.",
    "元に戻しました。",
  ],
  delete: ["Delete", "删除", "Eliminar", "삭제", "Xóa", "削除"],
  edit: ["Edit", "编辑", "Editar", "수정", "Sửa", "編集"],
  cancel: ["Cancel", "取消", "Cancelar", "취소", "Hủy", "キャンセル"],
  save: ["Save changes", "保存修改", "Guardar cambios", "변경 저장", "Lưu thay đổi", "変更を保存"],
  next: ["Up next", "下一节课", "A continuación", "다음 수업", "Tiếp theo", "次の授業"],
  inProgress: ["In progress", "正在上课", "En curso", "수업 중", "Đang học", "授業中"],
  inMinutes: [
    "In {n} min",
    "{n} 分钟后开始",
    "En {n} min",
    "{n}분 후",
    "Sau {n} phút",
    "あと{n}分",
  ],
  noClass: [
    "No classes on your schedule today.",
    "今天没有已安排的课程。",
    "No tienes clases programadas hoy.",
    "오늘 예정된 수업이 없어요.",
    "Hôm nay chưa có lớp trong lịch.",
    "今日の授業は登録されていません。",
  ],
  classDone: [
    "Today's classes are finished.",
    "今天的课程已结束。",
    "Las clases de hoy han terminado.",
    "오늘 수업이 끝났어요.",
    "Các lớp hôm nay đã kết thúc.",
    "今日の授業は終わりました。",
  ],
  noClassHint: [
    "Your weekly timetable keeps this view up to date.",
    "添加每周课表后，这里会自动显示当天安排。",
    "Tu horario semanal actualiza esta vista.",
    "주간 시간표를 추가하면 오늘 일정이 자동으로 표시돼요.",
    "Thêm lịch học hàng tuần để tự động hiển thị lịch hôm nay.",
    "週間時間割を登録すると、その日の予定がここに表示されます。",
  ],
  timetable: [
    "Weekly timetable",
    "每周课表",
    "Horario semanal",
    "주간 시간표",
    "Lịch học hàng tuần",
    "週間時間割",
  ],
  manage: [
    "Edit timetable",
    "管理课表",
    "Editar horario",
    "시간표 편집",
    "Quản lý lịch học",
    "時間割を編集",
  ],
  recurring: [
    "A recurring Monday–Friday timetable. Check your school calendar for holidays.",
    "课表按周一至周五重复显示，节假日请以学校校历为准。",
    "Un horario de lunes a viernes. Consulta los festivos en el calendario escolar.",
    "월요일부터 금요일까지 반복되는 시간표예요. 휴일은 학교 일정을 확인하세요.",
    "Lịch lặp lại từ thứ Hai đến thứ Sáu. Xem lịch trường để biết ngày nghỉ.",
    "月〜金の繰り返し時間割です。祝日・休校日は学校のカレンダーをご確認ください。",
  ],
  addClass: ["Add a class", "添加课程", "Añadir clase", "수업 추가", "Thêm lớp học", "授業を追加"],
  editClass: ["Edit class", "编辑课程", "Editar clase", "수업 수정", "Sửa lớp học", "授業を編集"],
  title: ["Class name", "课程名称", "Nombre de la clase", "수업 이름", "Tên lớp học", "授業名"],
  place: [
    "Location (optional)",
    "地点（选填）",
    "Lugar (opcional)",
    "장소 (선택)",
    "Địa điểm (tùy chọn)",
    "場所（任意）",
  ],
  start: ["Starts", "开始时间", "Inicio", "시작", "Bắt đầu", "開始"],
  end: ["Ends", "结束时间", "Fin", "종료", "Kết thúc", "終了"],
  day: ["Day", "星期", "Día", "요일", "Ngày", "曜日"],
  noDay: [
    "No classes added for this day.",
    "这天还没有添加课程。",
    "No hay clases añadidas para este día.",
    "이날 등록된 수업이 없어요.",
    "Chưa thêm lớp học cho ngày này.",
    "この日の授業はまだありません。",
  ],
  invalidTime: [
    "The end time must be after the start time.",
    "结束时间必须晚于开始时间。",
    "La hora de fin debe ser posterior a la de inicio.",
    "종료 시간은 시작 시간보다 늦어야 해요.",
    "Giờ kết thúc phải sau giờ bắt đầu.",
    "終了時刻は開始時刻より後にしてください。",
  ],
  overlap: [
    "This overlaps another class. Review the highlighted times before saving.",
    "与另一节课时间重叠。请核对标出的冲突时段后再保存。",
    "Coincide con otra clase. Revisa los horarios marcados antes de guardar.",
    "다른 수업과 겹쳐요. 표시된 시간을 확인한 뒤 저장하세요.",
    "Trùng giờ với một lớp khác. Kiểm tra khung giờ được đánh dấu trước khi lưu.",
    "別の授業と重なっています。印のついた時間を確認してから保存してください。",
  ],
  overlapWith: [
    "Conflicts with: {list}",
    "冲突课程：{list}",
    "Coincide con: {list}",
    "겹치는 수업: {list}",
    "Trùng với: {list}",
    "重複する授業：{list}",
  ],
  overlapConfirm: [
    "Save anyway? The new times still overlap.",
    "仍然保存吗？当前时间仍与其他课程重叠。",
    "¿Guardar de todos modos? Los horarios siguen coincidiendo.",
    "그래도 저장할까요? 시간이 여전히 겹칩니다.",
    "Vẫn lưu chứ? Khung giờ vẫn còn trùng.",
    "それでも保存しますか？時刻はまだ重なっています。",
  ],
  saveAnyway: [
    "Save anyway",
    "仍然保存",
    "Guardar de todos modos",
    "그래도 저장",
    "Vẫn lưu",
    "それでも保存",
  ],
  conflictMark: [
    "Time conflict",
    "时间冲突",
    "Conflicto de horario",
    "시간 충돌",
    "Trùng giờ",
    "時間の重複",
  ],
  classSaved: [
    "Timetable updated.",
    "课表已更新。",
    "Horario actualizado.",
    "시간표를 업데이트했어요.",
    "Đã cập nhật lịch học.",
    "時間割を更新しました。",
  ],
  classLimit: [
    "You can save up to 40 classes.",
    "最多保存 40 节课程。",
    "Puedes guardar hasta 40 clases.",
    "최대 40개 수업을 저장할 수 있어요.",
    "Lưu tối đa 40 lớp học.",
    "40件まで保存できます。",
  ],
  pin: [
    "Mark as important",
    "标记为重点",
    "Marcar como importante",
    "중요 표시",
    "Đánh dấu quan trọng",
    "重要としてマーク",
  ],
  unpin: [
    "Remove important mark",
    "取消重点标记",
    "Quitar marca de importante",
    "중요 표시 해제",
    "Bỏ đánh dấu quan trọng",
    "重要マークを解除",
  ],
  important: ["Important", "重点", "Importante", "중요", "Quan trọng", "重要"],
  dates: [
    "Dates to remember",
    "重要日期",
    "Fechas importantes",
    "중요한 날짜",
    "Ngày quan trọng",
    "大切な日程",
  ],
  viewGuide: [
    "Open the guide",
    "查看学生指南",
    "Abrir la guía",
    "안내 보기",
    "Mở cẩm nang",
    "ガイドを見る",
  ],
  noDates: [
    "No upcoming dates in the current calendar.",
    "当前校历暂无后续日期，请查看官方最新校历。",
    "No hay próximas fechas en el calendario actual.",
    "현재 달력에 예정된 날짜가 없어요.",
    "Lịch hiện tại chưa có ngày sắp tới.",
    "現在のカレンダーに今後の予定はありません。",
  ],
  calendarSource: [
    "Reference calendar: {name}. Confirm dates with your school.",
    "参考校历：{name}。具体安排请以所在学校为准。",
    "Calendario de referencia: {name}. Confirma las fechas con tu escuela.",
    "참고 일정: {name}. 학교에서 날짜를 확인하세요.",
    "Lịch tham khảo: {name}. Xác nhận ngày với trường của bạn.",
    "参考カレンダー：{name}。日程は所属校にご確認ください。",
  ],
  quick: [
    "Beyond your desk",
    "课余也有好去处",
    "Más allá del escritorio",
    "책상 밖으로",
    "Ngoài giờ học",
    "デスクの外へ",
  ],
  exploreHint: [
    "Libraries, parks, cafés, and places to take a break.",
    "图书馆、公园、咖啡馆，找到适合自己的去处。",
    "Bibliotecas, parques, cafés y lugares para descansar.",
    "도서관, 공원, 카페와 쉬어 갈 곳을 찾아보세요.",
    "Thư viện, công viên, quán cà phê và nơi nghỉ ngơi.",
    "図書館、公園、カフェ。ひと息つける場所を探そう。",
  ],
  loading: ["Loading…", "加载中…", "Cargando…", "불러오는 중…", "Đang tải…", "読み込み中…"],
  results: ["{n} places", "{n} 个地点", "{n} lugares", "장소 {n}곳", "{n} địa điểm", "{n}件の場所"],
  clear: [
    "Clear search",
    "清除搜索",
    "Borrar búsqueda",
    "검색 지우기",
    "Xóa tìm kiếm",
    "検索をクリア",
  ],
  search: [
    "Search places, areas, or activities",
    "搜索地点、区域或活动",
    "Buscar lugares, zonas o actividades",
    "장소, 지역, 활동 검색",
    "Tìm địa điểm, khu vực hoặc hoạt động",
    "場所・エリア・過ごし方を検索",
  ],
  backup: [
    "Backup & restore",
    "备份与恢复",
    "Copia y restauración",
    "백업 및 복원",
    "Sao lưu và khôi phục",
    "バックアップと復元",
  ],
  exportData: [
    "Export data",
    "导出数据",
    "Exportar datos",
    "데이터 내보내기",
    "Xuất dữ liệu",
    "データを書き出す",
  ],
  importData: [
    "Import data",
    "导入数据",
    "Importar datos",
    "데이터 가져오기",
    "Nhập dữ liệu",
    "データを取り込む",
  ],
  exportDone: [
    "Backup downloaded.",
    "备份文件已下载。",
    "Copia descargada.",
    "백업 파일을 내려받았어요.",
    "Đã tải tệp sao lưu.",
    "バックアップをダウンロードしました。",
  ],
  importHint: [
    "Choose a Eugene Desk backup file to restore on this device.",
    "选择一份 Eugene Desk 备份文件，恢复到当前设备。",
    "Elige un archivo de copia de Eugene Desk para restaurar en este dispositivo.",
    "이 기기에 복원할 Eugene Desk 백업 파일을 선택하세요.",
    "Chọn tệp sao lưu Eugene Desk để khôi phục trên thiết bị này.",
    "この端末に復元する Eugene Desk のバックアップを選んでください。",
  ],
  importPreview: [
    "This will replace everything saved in this browser with: {notes} to-dos, {classes} classes, {grades} grades across four school levels.",
    "将用以下内容替换当前浏览器中的全部书桌数据：{notes} 条待办、{classes} 节课程、{grades} 条成绩（四个学段合计）。",
    "Esto reemplazará todo lo guardado en este navegador por: {notes} tareas, {classes} clases y {grades} notas en los cuatro niveles.",
    "이 브라우저에 저장된 모든 데이터를 다음으로 바꿉니다: 할 일 {notes}개, 수업 {classes}개, 성적 {grades}개(네 단계 합계).",
    "Thao tác này sẽ thay toàn bộ dữ liệu trong trình duyệt bằng: {notes} việc cần làm, {classes} lớp học, {grades} điểm (cả bốn bậc học).",
    "このブラウザに保存された内容をすべて置き換えます：やること {notes}件、授業 {classes}件、成績 {grades}件（4区分合計）。",
  ],
  importStageLine: [
    "{level}: {notes} to-dos · {classes} classes",
    "{level}：待办 {notes} · 课程 {classes}",
    "{level}: {notes} tareas · {classes} clases",
    "{level}: 할 일 {notes} · 수업 {classes}",
    "{level}: {notes} việc · {classes} lớp",
    "{level}：やること {notes} · 授業 {classes}",
  ],
  importConfirm: [
    "Replace saved data",
    "确认替换",
    "Reemplazar datos",
    "데이터 교체",
    "Thay thế dữ liệu",
    "データを置き換える",
  ],
  importDone: [
    "Data restored.",
    "数据已恢复。",
    "Datos restaurados.",
    "데이터를 복원했어요.",
    "Đã khôi phục dữ liệu.",
    "データを復元しました。",
  ],
  importUndo: [
    "Undo import",
    "撤销本次导入",
    "Deshacer importación",
    "가져오기 취소",
    "Hoàn tác nhập",
    "取り込みを元に戻す",
  ],
  importUndone: [
    "Previous data restored.",
    "已恢复导入前的数据。",
    "Se restauraron los datos anteriores.",
    "가져오기 전 데이터로 되돌렸어요.",
    "Đã khôi phục dữ liệu trước khi nhập.",
    "取り込み前のデータに戻しました。",
  ],
  dismissUndo: [
    "Dismiss undo",
    "关闭撤销",
    "Cerrar deshacer",
    "실행 취소 닫기",
    "Đóng hoàn tác",
    "取り消しを閉じる",
  ],
  importBadJson: [
    "That file is not readable JSON. Nothing was changed.",
    "这个文件不是可读的 JSON，当前数据未改动。",
    "Ese archivo no es JSON legible. No se cambió nada.",
    "읽을 수 있는 JSON이 아니에요. 데이터는 그대로예요.",
    "Tệp không phải JSON hợp lệ. Chưa thay đổi gì.",
    "読み取れる JSON ではありません。データは変更していません。",
  ],
  importBadShape: [
    "This does not look like an Eugene Desk backup. Nothing was changed.",
    "这不像是 Eugene Desk 的备份文件，当前数据未改动。",
    "Esto no parece una copia de Eugene Desk. No se cambió nada.",
    "Eugene Desk 백업처럼 보이지 않아요. 데이터는 그대로예요.",
    "Đây không giống tệp sao lưu Eugene Desk. Chưa thay đổi gì.",
    "Eugene Desk のバックアップには見えません。データは変更していません。",
  ],
  importBadVersion: [
    "This backup format is not supported yet. Nothing was changed.",
    "暂不支持此备份格式版本，当前数据未改动。",
    "Este formato de copia aún no es compatible. No se cambió nada.",
    "아직 지원하지 않는 백업 형식이에요. 데이터는 그대로예요.",
    "Định dạng sao lưu này chưa được hỗ trợ. Chưa thay đổi gì.",
    "この形式のバックアップには未対応です。データは変更していません。",
  ],
  importBadStages: [
    "The backup is missing school-level data. Nothing was changed.",
    "备份缺少学段数据，当前数据未改动。",
    "Faltan datos de nivel escolar en la copia. No se cambió nada.",
    "백업에 학교 단계 데이터가 없어요. 데이터는 그대로예요.",
    "Bản sao lưu thiếu dữ liệu bậc học. Chưa thay đổi gì.",
    "バックアップに学校区分のデータがありません。データは変更していません。",
  ],
  importBadTimes: [
    "A class time in the backup is invalid. Nothing was changed.",
    "备份里有无效的课程时间，当前数据未改动。",
    "Hay un horario de clase inválido en la copia. No se cambió nada.",
    "백업에 잘못된 수업 시간이 있어요. 데이터는 그대로예요.",
    "Có giờ học không hợp lệ trong bản sao lưu. Chưa thay đổi gì.",
    "バックアップに無効な授業時間が含まれています。データは変更していません。",
  ],
  importBadGrades: [
    "A grade entry in the backup is invalid. Nothing was changed.",
    "备份里有无效的成绩记录，当前数据未改动。",
    "Hay una nota inválida en la copia. No se cambió nada.",
    "백업에 잘못된 성적 항목이 있어요. 데이터는 그대로예요.",
    "Có mục điểm không hợp lệ trong bản sao lưu. Chưa thay đổi gì.",
    "バックアップに無効な成績があります。データは変更していません。",
  ],
} as const satisfies Record<string, readonly [string, string, string, string, string, string]>;

const index: Record<Lang, number> = { en: 0, zh: 1, es: 2, ko: 3, vi: 4, ja: 5 };
export type DeskCopyKey = keyof typeof copy;
export function deskText(lang: Lang, key: DeskCopyKey, vars: Record<string, string | number> = {}) {
  return copy[key][index[lang]].replace(/\{(\w+)\}/g, (_, name: string) =>
    String(vars[name] ?? ""),
  );
}

export function dayName(lang: Lang, day: string) {
  const n = ["mon", "tue", "wed", "thu", "fri"].indexOf(day);
  return new Intl.DateTimeFormat(lang === "zh" ? "zh-CN" : lang, {
    weekday: "short",
    timeZone: "UTC",
  }).format(new Date(Date.UTC(2026, 0, 5 + Math.max(n, 0))));
}
