/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampusRouteImport } from './routes/campus'
import { Route as GpaRouteImport } from './routes/gpa'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as TownRouteImport } from './routes/town'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusRoute = CampusRouteImport.update({
  id: '/campus',
  path: '/campus',
  getParentRoute: () => rootRouteImport,
} as any)
const GpaRoute = GpaRouteImport.update({
  id: '/gpa',
  path: '/gpa',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const TownRoute = TownRouteImport.update({
  id: '/town',
  path: '/town',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campus': typeof CampusRoute
  '/gpa': typeof GpaRoute
  '/guide': typeof GuideRoute
  '/town': typeof TownRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campus': typeof CampusRoute
  '/gpa': typeof GpaRoute
  '/guide': typeof GuideRoute
  '/town': typeof TownRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campus': typeof CampusRoute
  '/gpa': typeof GpaRoute
  '/guide': typeof GuideRoute
  '/town': typeof TownRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/campus' | '/gpa' | '/guide' | '/town'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/campus' | '/gpa' | '/guide' | '/town'
  id: '__root__' | '/' | '/campus' | '/gpa' | '/guide' | '/town'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampusRoute: typeof CampusRoute
  GpaRoute: typeof GpaRoute
  GuideRoute: typeof GuideRoute
  TownRoute: typeof TownRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus': {
      id: '/campus'
      path: '/campus'
      fullPath: '/campus'
      preLoaderRoute: typeof CampusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gpa': {
      id: '/gpa'
      path: '/gpa'
      fullPath: '/gpa'
      preLoaderRoute: typeof GpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/town': {
      id: '/town'
      path: '/town'
      fullPath: '/town'
      preLoaderRoute: typeof TownRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampusRoute: CampusRoute,
  GpaRoute: GpaRoute,
  GuideRoute: GuideRoute,
  TownRoute: TownRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
